name: Nix CI

on:
  push:
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  upload-deb:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true
    - run: sudo apt-get install -y reprepro fuse
    - run: sudo wget --output-document=/usr/bin/goofys https://github.com/kahing/goofys/releases/latest/download/goofys
    - run: sudo chmod +x /usr/bin/goofys
    - run: dpkg --info bundle.deb
    - name: Assume the AWS role
      continue-on-error: true
      id: configure-aws-credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::223121549624:role/hhvm-github-actions
        aws-region: us-west-2
    - name: Decrypt the GPG key
      if: steps.configure-aws-credentials.outcome == 'success'
      run: |
        set -o pipefail
        GPG_KEY_FILE="$(mktemp)" &&
        aws kms decrypt \
            --ciphertext-blob "fileb://$PWD/gpg-key.kms-ciphertext" \
            --query Plaintext \
            --output text |
        base64 --decode > "$GPG_KEY_FILE" &&
        echo "GPG_KEY_FILE=$GPG_KEY_FILE" >> $GITHUB_ENV
    - name: Upload the deb package
      if: steps.configure-aws-credentials.outcome == 'success'
      run: |
        set -e
        sudo mkdir /mnt/hhvm-downloads
        sudo chown "$USER" /mnt/hhvm-downloads
        goofys -f hhvm-downloads /mnt/hhvm-downloads
        mkdir -p /mnt/hhvm-downloads/test-universal-packages
        echo 'Hello, World!' > /mnt/hhvm-downloads/test-universal-packages/hello

