name: Nix CI

on:
  push:
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  upload-deb:
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt-get install s3fs
    - uses: actions/checkout@v3
      with:
        lfs: true
    - run: dpkg --info bundle.deb
    - name: Assume the AWS role
      continue-on-error: true
      id: configure-aws-credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::223121549624:role/hhvm-github-actions
        aws-region: us-west-2
    - name: Decrypt the GPG key
      if: steps.configure-aws-credentials.outcome == 'success'
      run: |
        set -o pipefail
        GPG_KEY_FILE="$(mktemp)" &&
        aws kms decrypt \
            --ciphertext-blob "fileb://$PWD/gpg-key.kms-ciphertext" \
            --query Plaintext \
            --output text |
        base64 --decode > "$GPG_KEY_FILE" &&
        echo "GPG_KEY_FILE=$GPG_KEY_FILE" >> $GITHUB_ENV
    - name: Upload the deb package
      if: steps.configure-aws-credentials.outcome == 'success'
      run: |
        sudo mkdir /mnt/test-universal-packages &&
        AWSACCESSKEYID="$AWS_ACCESS_KEY_ID" \
        AWSSECRETACCESSKEY="$AWS_SECRET_ACCESS_KEY" \
        AWSSESSIONTOKEN="$AWS_SESSION_TOKEN" \
        sudo s3fs hhvm-downloads:/test-universal-packages /mnt/test-universal-packages -f
