name: Nix CI

on:
  push:
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  upload-deb:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true
    - uses: cachix/install-nix-action@v15
      with:
        extra_nix_config: |
          extra-access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          extra-experimental-features = nix-command flakes
          extra-substituters = s3://hhvm-nix-cache?region=us-west-2&endpoint=hhvm-nix-cache.s3-accelerate.amazonaws.com
          extra-trusted-substituters = s3://hhvm-nix-cache?region=us-west-2&endpoint=hhvm-nix-cache.s3-accelerate.amazonaws.com
          extra-trusted-public-keys = hhvm-nix-cache-1:MvKxscw16fAq6835oG8sbRgTGITb+1xGfYNhs+ee4yo=
    - run: nix profile install nixpkgs#s3fs
    - run: dpkg --info bundle.deb
    - name: Assume the AWS role
      continue-on-error: true
      id: configure-aws-credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::223121549624:role/hhvm-github-actions
        aws-region: us-west-2
    - name: Decrypt the GPG key
      if: steps.configure-aws-credentials.outcome == 'success'
      run: |
        set -o pipefail
        aws kms decrypt \
            --ciphertext-blob "fileb://$PWD/gpg-key.kms-ciphertext" \
            --query Plaintext \
            --output text |
        base64 --decode |
        gpg --import
    - name: Upload the deb package
      if: steps.configure-aws-credentials.outcome == 'success'
      run: |
        set -e
        HHVM_DOWNLOAD="$(mktemp --directory)"
        ls -a "$HHVM_DOWNLOAD"
        AWSACCESSKEYID="$AWS_ACCESS_KEY_ID" \
        AWSSECRETACCESSKEY="$AWS_SECRET_ACCESS_KEY" \
        AWSSESSIONTOKEN="$AWS_SESSION_TOKEN" \
        s3fs -o "endpoint=$AWS_REGION" -o use_session_token hhvm-downloads "$HHVM_DOWNLOAD"
        mkdir -p "$HHVM_DOWNLOAD/test-universal-packages"
        echo 'Hello, World!' > "$HHVM_DOWNLOAD/test-universal-packages/hello2"

