name: Nix CI

on:
  push:
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  upload-deb:
    runs-on: ubuntu-latest
    container:
      image: nixos/nix
    steps:
    - run: nix-env -iA nixos.s3fs
    - uses: actions/checkout@v3
      with:
        lfs: true
    - run: dpkg --info bundle.deb
    - name: Assume the AWS role
      continue-on-error: true
      id: configure-aws-credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::223121549624:role/hhvm-github-actions
        aws-region: us-west-2
    - name: Decrypt the GPG key
      if: steps.configure-aws-credentials.outcome == 'success'
      run: |
        set -o pipefail
        GPG_KEY_FILE="$(mktemp)" &&
        aws kms decrypt \
            --ciphertext-blob "fileb://$PWD/gpg-key.kms-ciphertext" \
            --query Plaintext \
            --output text |
        base64 --decode > "$GPG_KEY_FILE" &&
        echo "GPG_KEY_FILE=$GPG_KEY_FILE" >> $GITHUB_ENV
    - name: Upload the deb package
      if: steps.configure-aws-credentials.outcome == 'success'
      run: |
        set -e
        sudo tee /etc/passwd-s3fs <<EOF
        $AWS_ACCESS_KEY_ID:$AWS_SECRET_ACCESS_KEY
        EOF
        sudo chmod 600 /etc/passwd-s3fs
        sudo mkdir /mnt/test-universal-packages
        AWSSESSIONTOKEN=$AWS_SESSION_TOKEN sudo s3fs hhvm-downloads:/test-universal-packages /mnt/test-universal-packages -f -o allow_other -o "uid=$UID" -o endpoint=us-west-2
        sudo chown "$USER" /mnt/test-universal-packages/
        echo 'Hello, World!' > /mnt/test-universal-packages/hello
